baseURL: 'https://hlth.github.io/'
title: 'Mind & Market | Hugo Angelmar'
paginate: 5
languageCode: 'en-us'
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: "G-VSB6CMVPCB"

minify:
  disableXML: true
  minifyOutput: true

twitter: 'hlth'               # twitter.com/YOUR_TWITTER_ID
github: 'hlth'                # github.com/YOUR_GITHUB_ID
linkedin: 'hugoangelmar'      # linkedin.com/in/YOUR_LINKEDIN_ID
rss: true                     # show rss icon

# misc
disableHLJS: false                       # disable highlight.js
disablePostNavigation: false             # disable post navigation
monoDarkIcon: true                       # show monochrome dark mode icon
math: true                               # enable KaTeX math typesetting globally


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 'Mind & Market - Hugo Angelmar'
  description: "Professional & personal experiences, insights and stories captured from two decades in tech."
  keywords: [Blog, Portfolio, Tech, Venture, SaaS, Growth]
  author: Me

  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShareButtons: ["linkedin", "twitter","facebook","reddit"] # To customize which share buttons to be enabled on page
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false


  label:
    text: "Mind & Market"
    icon: "images/home_icon4.png"
    iconHeight: 35


 # profile-mode
  profileMode:
    enabled: true  # needs to be explicitly set
    title: Hugo Angelmar
    subtitle: "Professional & personal experiences, insights and stories captured from two decades in tech."
    imageUrl: "images/hlth_icon.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Hugo Angelmar Profile Picture
    buttons:
      - name: Posts
        url: posts
      - name: About
        url: about

  # home-info mode
  homeInfoParams:
    Title: "Mind & Market"
    Content: Professional & personal experiences, insights and imaginary stories captured from two decades in tech. 
  socialIcons:
  - name: linkedin
    url: "https://www.linkedin.com/in/hugoangelmar"
  - name: github
    url: "https://github.com/hlth"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/home_icon4.png"
    #favicon16x16: "<link / abs url>"
    #favicon32x32: "<link / abs url>"
    #apple_touch_icon: "<link / abs url>"
    #safari_pinned_tab: "<link / abs url>"

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary